# Generated by Django 4.2.4 on 2023-09-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='tags',
        ),
        migrations.AddField(
            model_name='tags',
            name='tags',
            field=models.CharField(default=1, max_length=256, verbose_name='Тег'),
            preserve_default=False,
        ),
    ]
