# Generated by Django 4.2.4 on 2023-09-20 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_tags_options_tags_name_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='name_text',
        ),
    ]
