# Generated by Django 4.2.4 on 2023-09-20 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_tags_test1_articles_tags_alter_tags_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='test1',
            new_name='articl',
        ),
    ]
