# Generated by Django 4.2.4 on 2023-09-20 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_test1_tags_articl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='articl',
            new_name='article',
        ),
    ]
