# Generated by Django 4.2.4 on 2023-09-21 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_tags_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='article',
        ),
        migrations.AlterField(
            model_name='tags',
            name='is_main',
            field=models.BooleanField(verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articles_tags', verbose_name='Категории'),
        ),
    ]
