# Generated by Django 4.2.4 on 2023-09-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_tags_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_tags',
            name='articles',
            field=models.ManyToManyField(related_name='tag', to='articles.article'),
        ),
    ]
