# Generated by Django 4.2.4 on 2023-09-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_articles_tags_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles_tags',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='tags',
            name='title',
            field=models.CharField(default=1, max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
