# Generated by Django 4.2.4 on 2023-09-21 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_articles_tags_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles_tags',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='tags',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articles_tags', verbose_name='Тег'),
        ),
    ]
