# Generated by Django 4.2.4 on 2023-09-21 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_remove_articles_tags_is_main_alter_tags_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='article',
        ),
    ]
