# Generated by Django 4.2.4 on 2023-09-21 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_remove_tags_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.articles_tags'),
        ),
    ]
