# Generated by Django 4.2.4 on 2023-09-21 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_alter_tags_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='tags',
        ),
    ]
