# Generated by Django 4.2.4 on 2023-09-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_remove_tags_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='is_main',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
