# Generated by Django 4.2.4 on 2023-09-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_alter_scope_is_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles_Tags',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='title',
            new_name='scopes',
        ),
    ]
