# Generated by Django 4.2.4 on 2023-09-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_remove_scope_scopes_article_scopes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='article',
        ),
        migrations.AddField(
            model_name='scope',
            name='scopes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.tag', verbose_name='Тег'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(to='articles.scope'),
        ),
    ]
