# Generated by Django 4.2.4 on 2023-09-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_remove_scope_article_scope_scopes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='scopes',
        ),
        migrations.AddField(
            model_name='scope',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Статья'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.tag', verbose_name='Тег'),
            preserve_default=False,
        ),
    ]
