# Generated by Django 4.2.4 on 2023-09-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_remove_scope_scopes_scope_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='article',
        ),
        migrations.AddField(
            model_name='scope',
            name='article_id',
            field=models.IntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(to='articles.scope'),
        ),
    ]
