# Generated by Django 4.2.4 on 2023-09-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0032_remove_scope_article_scope_article_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='scopes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.tag', verbose_name='Тег'),
            preserve_default=False,
        ),
    ]
