# Generated by Django 4.2.4 on 2023-09-21 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_scope_scopes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='scopes',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='article_id',
        ),
        migrations.AddField(
            model_name='scope',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(through='articles.Scope', to='articles.tag'),
        )
    ]
