# Generated by Django 4.2.4 on 2023-09-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_rename_scopes_scope_tag_remove_scope_article_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main']},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
