# Generated by Django 4.2.4 on 2023-09-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_teacher_for_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teachers',
            field=models.ManyToManyField(related_name='students', to='school.student'),
        ),
        migrations.DeleteModel(
            name='Teacher_for_student',
        ),
    ]
