# Generated by Django 4.2.4 on 2023-09-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_student_teachers_teacher_teachers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teachers',
            new_name='students',
        ),
    ]
