# Generated by Django 4.2.4 on 2023-09-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_teachers_teacher_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='students',
            new_name='student',
        ),
    ]
